stages:
  data_ingestion:
    cmd: python3 src/data/data_ingestion.py
    deps:
    - src/common/utils.py
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/interim
    - data/raw
