stages:
  data_ingestion:
    cmd: python3 src/data/data_ingestion.py
    deps:
    - src/common/utils.py
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/interim
    - data/raw
  data_transformation:
    cmd: python3 src/transformation/data_transformation.py
    deps:
    - data/interim
    - src/common/utils.py
    - src/transformation/data_transformation.py
    outs:
    - data/processed
  train_model:
    cmd: python3 src/models/train_model.py
    deps:
    - data/processed
    - src/common/utils.py
    - src/models/train_model.py
    params:
    - model_tuning.models
    outs:
    - data/models
  model_registration:
    cmd: python3 src/models/register_model.py
    deps:
    - data/models
    - reports/experiment_info.json
    - src/models/register_model.py
